### PR TITLE
Syn to Runalyze (Issue #300)

### PR DESCRIPTION
**Pull request by rickyepoderi**
Issue #300 : Sync to runalyze.

### CODE REVIEW

**Comment by Marx2** [comment]
Great! I hope it will be in next version

**Comment by rickyepoderi** [comment]
I have just pushed my repo. One change was added, the "type" of the activity is blank now. I have changed my mind and now no type is sent (just running). You can later edit the activity in runalyze and assign the type you want.

There is an error in the integration (but I don't know ehat), please comment me any change.

**Comment by jonasoreland** [comment]
travis failed...
looked at it briefly, don't understand why.

**Comment by rickyepoderi** [comment]
Ok, if you see something wrong just say it and I'll do the changes (I have little experience with android and the annoying android-studio).

**Comment by VCleemput** [comment]
Hey everyone,
I'm completely new to this, so sorry if I'm being to intrusive.
I was wondering, if it would be possible to do send the type of sport, since runalyze doesn't calculate VDOT if no trainingtype is specified.
Thanks!

**Comment by rickyepoderi** [comment]
In runalyze there are two fields to categorize the sport (sport and type) but in runnerup there is only one. At first I did two different methods to pass both parameters (the methods are still there):

* sport: [runnerupSport2RunalyzeSport](https://github.com/rickyepoderi/runnerup/blob/master/app/src/org/runnerup/export/format/RunalyzePost.java#L295)
* type: [runnerupSport2RunalyzeType](https://github.com/rickyepoderi/runnerup/blob/master/app/src/org/runnerup/export/format/RunalyzePost.java#L327)

The problem is we have to map the values in code (with the problems of ids and so on) and besides for the type we have nothing. If you see the second method just passes always 1 which is _jogging_ for _running_ and nothing for the rest of sports. That is why I decided to remove this field when I realized it was not compulsory, and don't pass anything for the type. You need to manually set this field later after uploading to the activity in runalyze. I don't know, if you think is better to pass something (_jogging_ or whatever) it is just reverting this commit: https://github.com/jonasoreland/runnerup/pull/437/commits/8056ed51173edbc3e4df1b0cfac960d8681b415c

One off-topic question, I usually use f-droid in my phone and runnerup is not being updated for a long time (I'm using my own compiled app)... Anyone knows who is in charge of uploading this app to f-droid? I want to go back to f-droid version. :wink:

**Comment by VCleemput** [comment]
Aha, I knew there would probably be a reason :)
Also thanks for the commit-number. I'm going to try and see what it's like.

**Comment by Marx2** [comment]
Can't we add an option for mapping sport type? It even can be a magic number of Running sport type, because it's set once and will not change. 
It will be much more convenient to read somehow this number and set it in properties of account, than changing sport type  every time new activity is uploaded.

**Comment by rickyepoderi** [comment]
IMHO adding a configuration for the type is a bit strange, think that the account screen is shared to all account backends (garmin, runalyze, strava, and so on).

Remember that runalyze uses IDs for sport and type (a number which is the PK in the database) and in my straight forward integration I'm just using default IDs created by the default installation (I mean that if you start deleting and adding sports and types in the server you can screw the integration up). The correct way is having an API (restful or whatever) to discover sports and types defined in runalyze and try to find a more intelligent strategy to map them. The guys in runalyze know this problem and in a future version the API will be provided. Until that time I think we have to keep the integration as simple as possible, so if you think that the type should be sent I'd just choose one default ID (jogging, tempo run or whatever) and fill the type with it.

Open a new issue with the problem and we can talk and decide something.

**Pull request merged**
