### PR TITLE
Advanced workout creator

### PR DESCRIPTION
**Pull request by paradix**
New Feature - advanced workout creator (fixed issue #173).
 - Includes new activity for creating advanced workouts that can be started from workout manager.
 - You can add steps and repeat steps by clicking the proper button.
 - Adding steps underneath the repeat step can be done by a long-click
 - Deleting of steps is done by a long-click

### CODE REVIEW

**Comment by jonasoreland** [comment]
fyi: glanced, and all look good.
i'll pull and test it some manually before merging though.

/Jonas

**Comment by paradix** [comment]
Great, I have already made some manual tests. Check please if the changes made to the WorkoutSerializer.createJSON don't mess with the workouts downloaded from garmin, because I was only able to test with the one supplied with the app.

**Comment by jonasoreland** [comment]
comments (after test)
1) i can scroll down the list *under* the buttons on the manage workout screen
2) i get yes/no instead of OK/cancel when I create a workout (set name)
3) how do I add a step under a repeat (i.e so that it's repeated)
4) it's (to me) totally unobvious that long press means delete of step
and...no "are you sure" when it happens.
5) I expected save to close the edit-screen, shouldn't it ?

6) code wise: when are the changes to WorkoutSerializer.createJSON needed ?

/Jonas

**Comment by paradix** [comment]
1), 2), 5) I'll check this issues and fix them.
3) Long click on the repeat and You get a popup.
4) yes it's not so obvious I also see it, but I couldn't find any other way to delete single steps. I'm not that handy in UI programming, maybe You would have an better solution?

**Comment by jonasoreland** [comment]
GUI suggestions...

1) would it be possible to have a "+" button on the repeat-step to add a step to the "repeat"
and maybe have the same "+" under all existing steps to add a new "in the end".

2) along the same lines, a "-" button/icon e.g on the left of each step.button could be delete...
(with a "Do you want to delete this step: "OK", "OK - don't ask again", "Cancel" popup)
 
3) and...moving of steps would also be nice...

---

what do you think about those suggestions? good/bad hard/easy

**Comment by paradix** [comment]
Well everything is doable - it's always the question of time and material :)
I will see what I can do about your suggestions - seems like a nice idea.

**Comment by paradix** [comment]
Could you please tell me more about the "in the end" step? I didn't realize there can be something more added after each step.

**Comment by jonasoreland** [comment]
i simply meant a "+" button/icon...pressing it would add a step

**Comment by paradix** [comment]
Ahh ok, I just read your comment again and I finally understood what you meant :)

**Comment by paradix** [comment]
now most of your suggestions are done. I left the moving part for later.
Waiting for further comment's

**Comment by jonasoreland** [comment]
cool! that was fast!
will try to find time tonight to check it out...

/Jonas

**Comment by jonasoreland** [comment]
Hi there.
Much better!

Comments:
1) can you make the indentation bigger so that it's more obvious which steps are repeated ?
(i think that is quite important)

2) not so important: would it make sense to remove the "+" from the right of a non-repeat step,
and instead put it underneath the last step in the sequence ?

3) not super important: the "+" and "-" buttons are dead ugly if you ask me.
How about a round background image (can be done with shape) in e.g green for add and red for remove. (think the new "material design" thing, but with runnerup standard color)

**Comment by paradix** [comment]
1) Maybe sub-steps could get another shade of Gray (LOL) instead?
2) that was also my primary idea, but I thought this way you can easily add steps inbeetween
3) 100% right - will think about something

**Comment by jonasoreland** [comment]
1) color change is fine by me too...
just something so that you see....now i missed it at first...and second time...and third time,
and then I saw it.

2) ok...fair enough

3) ok

/Jonas

**Comment by paradix** [comment]
Can you give me any hints on how to create image's that can be used as buttons? Did You do it in Gimp or something similar?

**Comment by jonasoreland** [comment]
how about the one in wear/src/main/res/drawable/circle.xml ?

basic shapes can be defined in xml, no need for actual bitmap.

/Jonas

**Comment by paradix** [comment]
I didn't mean the circle button, but the colour of the step button

**Comment by jonasoreland** [comment]
ahh...that is likely one of the title_spinner*.png i think...
but modifying these seems...not optimal i think.

maybe larger indentation is better then ??

/Jonas

**Comment by paradix** [comment]
Yeah will probably do that, but this will lead to text wrapping and will make the StepButton twice that high.

**Comment by jonasoreland** [comment]
commonly or only with double repeat ??
(or with which strings ??)

i use a background color in the "Advanced"-tab.
maybe that makes it easier to see repeat indentation...maybe :)

/Jonas

**Comment by paradix** [comment]
It will probably be only a problem for other languages e.g. Polish :) The translated words for the intensity are being wrapped, that's why I was thinking about another colour of the StepButton/TitleSpinner for the repeated steps. 

This would require to create another png image in a different colour. That's why switching to holo theme would be nice, or is that out of the question?

**Comment by jonasoreland** [comment]
i'd say that switching themes as part of this feature is out of the
question...
though, one(you?) can work on that as another PR

/Jonas

**Comment by paradix** [comment]
I didn't mean this as a part of this issue, just in general. 
I'll finish this one probably with making the padding of sub-steps bigger.
After that I'll do some reading about the holo themes and see what can be done, but this will probably mean a lot of work.

**Comment by jonasoreland** [comment]
right, sounds good.
i don't have anything "against" holo-theme...i just haven't spent time on
it...

https://github.com/jonasoreland/runnerup/issues/158 is one thing that might
be good for broader adoption...
if you're looking for work :)

/Jonas

btw, are you member of
https://plus.google.com/u/0/communities/112040124647770742805 ?
i think i'll do a new beta this weekend or so...

**Comment by paradix** [comment]
Have you had any chance to review/test the last changes?

**Comment by jonasoreland** [comment]
looked good
merged
and please tell when a new reviewable version is available...it's easy to miss.

Thanks! Great work

/Jonas

**Pull request merged**
