### PR TITLE
WIP Android studio 3.2

### PR DESCRIPTION
**Pull request by gerhardol**
Support Android Studio 3.2

Enables latest emulators

### CODE REVIEW

**Comment by gerhardol** [comment]
@12people Can you please test on Froyo?

**Comment by 12people** [comment]
Builds and runs just fine. Anything I should test in particular?

**Comment by gerhardol** [comment]
Basically, if it builds and starts recording in Froyo, it should be fine.
The force use of older compatibility lib for Froyo build with newer compile sdk is not working well in Pie (at least in the emulator), the notification channel workaround is not working.

**Comment by 12people** [comment]
All this worked well on the Froyo emulator for me.

**Comment by gerhardol** [comment]
Build fails due to lint, fixed in #739

**Pull request merged**
