### PR TITLE
Proposal PR for issue #153

### PR DESCRIPTION
**Pull request by paradix**

### CODE REVIEW

**Comment by jonasoreland** [comment]
comments:
1) i think most look ok.
2) i want to split into significantly smaller pieces, merged one at a time.
3) first I want polish translations and NO OTHER CHANGES.
4) then I want plurals handling and no other changes and FOR ALL LANGUAGES
(fixed on the tx site too).
5) then I want to look at what's remaining in this patch.

sounds ok ?

/Jonas

**Comment by jonasoreland** [comment]
fyi: merged the polish translations from tranferix. 
great work!

**Comment by paradix** [comment]
Great. Thanks for doing the splitting. I might do some changes to the translation in time when I see the need after I used the app during trainings. 

Any other things I could help with?

**Comment by paradix** [comment]
Will you be able to integrate the "plurals" into transifex after it was committed into git?

**Comment by jonasoreland** [comment]
yes, you can push translations.

i.e you can make changes in git (plurals only, all languages)
i merge those changes
i can then push to transferix and github

/Jonas

**Comment by paradix** [comment]
Ok. I'll try to do the translation of the plurals for all languages. Will see what comes out ;)

On my today training I discovered a bug with the MessageFormat implementation. I'll need to review it again. I'll split the PRs into translation of plurals and the fixed MessageFormat implementation.

**Pull request closed without merging**
