### PR TITLE
Hide 'Discard' Button when editing existing advanced workouts

### PR DESCRIPTION
**Pull request by Upabjojr**
Responding to the idea of comment https://github.com/jonasoreland/runnerup/pull/984#issuecomment-731596314

### CODE REVIEW

**Review by gerhardol — COMMENTED** [review]
The Save button should be expanded, similar to other buttons

image

**Comment by Upabjojr** [comment]
> The Save button should be expanded, similar to other buttons

How do you do that?

**Comment by gerhardol** [comment]
> How do you do that?

Magic
Similar to the share/edit row before
INVISIBLE -> GONE addresses that

**Review by gerhardol — APPROVED** [review]
Will squash merge, unless manually squashed
Thanks!

**Pull request merged**
