### PR TITLE
Bpm fix

### LINKED ISSUE #187: formatHeartrate(CUE) gives exception
Settings=>Audio cues
Check lap heartrate
Press Push

    android.content.res.Resources$NotFoundException: Plural resource ID #0xa1 quantity=2131230726 item=other
            at android.content.res.Resources.getQuantityText(Resources.java:1474)
            at android.content.res.Resources.getQuantityString(Resources.java:1617)
            at org.runnerup.util.Formatter.formatHeartRate(Formatter.java:261)
            at org.runnerup.util.Formatter.format(Formatter.java:150)
            at org.runnerup.workout.feedback.AudioFeedback.getCue(AudioFeedback.java:104)
            at org.runnerup.workout.feedback.AudioFeedback.emit(AudioFeedback.java:112)
            at org.runnerup.view.AudioCueSettingsActivity$8$1.onInit(AudioCueSettingsActivity.java:408)
            at org.runnerup.view.AudioCueSettingsActivity$8.onPreferenceClick(AudioCueSettingsActivity.java:429)
            at android.preference.Preference.performClick(Preference.java:1054)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:229)

### PR DESCRIPTION
**Pull request by paradix**
fixes  #187

### CODE REVIEW

**Comment by jonasoreland** [comment]
1) great catch (the wrong order arguments!)
2) good to remove unused
3) BUT, is the move needed ?

/Jonas

**Comment by paradix** [comment]
3) needed - no, but at least strings used in cues are consistently in the appropriate resource

**Comment by jonasoreland** [comment]
fair enough...
i'll merge it

/Jonas

**Comment by jonasoreland** [comment]
i did following:
1) pull latest translations
2) merge this
3) push to github
4) push to transifex

**Comment by paradix** [comment]
Great. I'll check transifex randomly to see if all is fine.

**Pull request merged**
