### PR TITLE
SYNCHRONIZERS: update sports status

### PR DESCRIPTION
**Pull request by bagage**

### CODE REVIEW

**Comment by bagage** [comment]
bump here

**Comment by bagage** [comment]
I also have updated various file to use markdown syntax and rich text support.

**Comment by jonasoreland** [comment]
Hi, sorry for delay.

I think you miss interpreted my intentions with the SPORTS field.
I want what sports are supported for uploading.

E.g funbeat does NOT support uploading the sport types that you put in, right ?
it in fact only supports them for the feed...(which it in fact did before adding it to the sports-map)
make sense ?

the other changes look fine...
/Jonas

**Comment by bagage** [comment]
My bad for Funbeat, I updated it. Do you see any other errors???

**Comment by jonasoreland** [comment]
checked briefly...let merge this and we can fix errors

**Pull request merged**
