### PR TITLE
Lint cleanup travis

### PR DESCRIPTION
**Pull request by gerhardol**
This is similar to #333 (credit to @bagage) enabling lint in Travis builds

The difference is that 'MissingQuantity','ImpliedQuantity' is not included (as requested by @jonasoreland in #333), to be done later
A number of warnings have been eliminated too (more could be fixed, requires more testing).

Lint in AS and from gradle is not completely synced

Tested on Marschmallow only, but changes should not affect runtime...

### CODE REVIEW

**Comment by jonasoreland** [comment]
why have you removed 
> fatal 'NewApi', 'InlineApi'

iirc this is to prevent usage of api's that is not supported by minimum version.

**Comment by gerhardol** [comment]
Fatal anyway,  no need to add explicitly

**Comment by jonasoreland** [comment]
are you sure ??

we had numerous times that one accidentally used incorrect apis before
adding that
but it was a while ago...

/Jonas

**Comment by gerhardol** [comment]
I got newapi errors while eliminating lint warnings, can recheck tonight

**Comment by gerhardol** [comment]
Wrapup for the lintOptions change: 
That will promote the error/warning to fatal when lint is running

NewApi is error by default, so changing to fatal is not much change.
However InlineApi is warning by default and will therefore not result in an error. There are so many warnings that this will not be seen.
I will submit a new patch for this (maybe including more lint eliminations).

**Pull request merged**
