### PR TITLE
default audio scheme name

### PR DESCRIPTION
**Pull request by paradix**
Fixes issue #215

### CODE REVIEW

**Comment by jonasoreland** [comment]
I like the patch...but does it really fix the problem ?
I.e if you change language on phone, your default audio cue scheme shouldn't change, right ?
Don't we need to handle that specially ?

**Comment by paradix** [comment]
I'm still testing different issues with the language settings. We will see if I find any other problems.
For now the patch seem to work fine. I'll play around with the example you mention.

**Comment by paradix** [comment]
This patch handles the default scheme correctly even if you change the phone language.

**Comment by jonasoreland** [comment]
that is great! but how ?

**Comment by paradix** [comment]
the default values of the audio cue prefs are not stored in a seperate file but in the runnerup global prefs. So if the name of the "default" scheme is equal to "default" the global prefs file is returned.

This comparison is made on the values of:
1) the preference key pref_basic_audio (the value of the scheme selected in the spinner)
AND
2) the value of the string default_audio_scheme_name

If both are accessed through the resources and get translated to the global locale all is fine.

The problem was in the spinner value returning always "Default" instead of the translated string. When the string default_audio_scheme_name was translated (as for polish) the comparison was returning false and the app assumed it's not the default but a custom audio scheme.

That's my explanation for this.

**Comment by jonasoreland** [comment]
super, then I understand, thx!

/Jonas

**Pull request merged**
