### PR TITLE
start/end point type when downloading runkeeper

### PR DESCRIPTION
**Pull request by paradix**

### CODE REVIEW

**Comment by bagage** [comment]
Is not `else if` condition redundant with the `if` one?

```java
+            if (lat == null || lon == null) {
+              // ...
+            } else if (lat != null && lon != null) {
```

**Comment by paradix** [comment]
I'm sorry I'm pretty tired after 2 very long days at work, but how is it redundant?

**Comment by bagage** [comment]
Well if `latt == null || lon = null` is true, then `lat != null && lon != null` is necessary false (and vice versa). So this could only be rewrite using:

```java
+            if (lat == null || lon == null) {
+              // ...
+            } else {
```

**Comment by paradix** [comment]
Yeah you are absolutely right. 

16 cze 2015 22:05 Gautier Pelloux-Prayer <notifications@github.com> napisał(a):

**Pull request merged**
