### PR TITLE
Include format when creating a syncronizer

### LINKED ISSUE #931: FIXED: WebDAV not synchronizing when started manually
**This issue is for documentation to prevent multiple reports. I already fixed this issue.**

**Type:** BUG

**Problem:**
When you do not have an internet connection the activity will not get synchronized. There was a problem, that the format (tcx / gpx) was not correctly passed to the WebDavSyncronizer, leading to a success without uploading the file. This issue occured on manual sync only.

**How to reproduce:**
Start an activity and save it with no internet connection. Connect your internet and go to accounts. Select WebDav, choose upload and manually select the previous activity. The Upload will look like it's succeeded and disappears from the unsynced list but there will be no file on your WebDav.

**Related Content:**
adds uploads to WebDav #909
Include format when creating a syncronizer #932 (FIX)

### PR DESCRIPTION
**Pull request by DeveloperOl**
Resolves #931

### CODE REVIEW

**Comment by DeveloperOl** [comment]
I tested the WebDav account only. Please test other accounts, too before merging.

**Comment by gerhardol** [comment]
The correction is ensuring that DB.ACCOUNT.FORMAT is included in all queries so it is available for synchronizers.
I would prefer to use a common list instead, to ensure that this does not happen again.

FORMAT is used in few synchronizers, only File and Dropbox, the handling is similar so both the problem and the correction should be the same.

**Comment by gerhardol** [comment]
WebDAV/File/Dropbox should behave the same her.
There are some issues with refreshing, I do not see the problem always in older releases, but the change should be OK.

**Comment by gerhardol** [comment]
Thanks!

**Pull request merged**
