### PR TITLE
Download activities

### PR DESCRIPTION
**Pull request by paradix**
This are only changes around the RunKeeper downloader from Issue #196.
With this a base for all other services should be made.

### CODE REVIEW

**Comment by jonasoreland** [comment]
i glanced it yesterday (all in 2 minutes)...and think it looks good.
i'll try find time to look more carefully during weekend

**Comment by paradix** [comment]
OK, but don't merge it yet. I'm still testing and need to make sure no bugs were built in for the upload functionality.

**Comment by paradix** [comment]
I think it should be now ready for review.

**Comment by paradix** [comment]
I'm still tweaking on the activity compare method that is supposed to filter already present/downloaded activities.

**Comment by jonasoreland** [comment]
i haven't had time to read your patch yet, sorry :(

BUT, the DB.EXPORT.EXTERNAL_ID in DB.EXPORT.TABLE is supposed to be the
external id of the activity for a specific uploader.
E.g in your case the runkeeper id for an activity.

If we modify the uploaders to populate that field...the we don't need to
compare activities.
And for simplicify, we can say that we only support downloading activities
that are newer than the version that support downloading.

Makes sense ?

/Jonas

**Comment by paradix** [comment]
Well yes the use of the external_id seems like a good idea. But I'm assuming that not every activity has been uploaded with RunnerUp to every possible service. Hence there will not always be an external_id for comparison.

That's why I think it would be good to create some rules of similarity. 
For instance I have uploaded some activity created by RunnerUp to RunKeeper and I don't know why but RunKeeper says it's longer by few meter, or started a second later or the duration got messed up and is now of by some minutes.

We will probably newer get it 100% right, but close enough would be good enough.

**Comment by jonasoreland** [comment]
general comments: i think splitting this PR into several smaller is a good idea.

first pass comments:
1) license is missing on "all" new files, please make a separate PR to fix that

2) What is IObjectValues, I couldn't figure out if I had 10 guesses...how about a name that describes it
class DBEntity
{
  interface Insertable {
  };

  interface Updatable {
 };
};

3) How about renaming Uploader to Syncronizer (in separate commit/PR)
4) How about creating a DefaultSynchronizer which implements the interface,
and let classes extend it (possibly via FormCrawler) so we don't add empty methods
all over when adding new capabilities.
5) I strongly think that "persistActivity" should not reside inside RunKeeperSynchronizer,
isn't that the entire idea with the DB entities, RunKeeperSyncronizer creates an object,
that will be inserted somewhere else.

6) random newlines/space/bracket changes here and there should be move to separate PR or removed all together

**Comment by paradix** [comment]
I agree on all your point. I'll do the changes in the next iteration as there will be further refactoring necessary.

Ad 2) The idea was to create a common interface for the Db entities to be able to make bulk updates/inserts. The name obviously could be more speaking.

Ad 5) Yes, but than it should be refactored so it will get all the entities as argument and insert them properly updating the primary and foreign keys. 

BTW. why are there no foreign keys and constraints in the runnerup db?

**Comment by paradix** [comment]
As for 3) I got a question.
Renaming Uploader to Synchronizer is one thing, but all the variable names are also often called [prefix]uploader[suffix] 
Also the UploadManager could be renamed to SyncManager, this would make the change even bigger.

Do you want all this to be done?

**Comment by jonasoreland** [comment]
if we *only* do renames in one PR i think that is fine, yes

/Jonas

**Comment by paradix** [comment]
Most points are done. The renaming will follow when all other PRs are accepted.

**Pull request closed without merging**
