### PR TITLE
Dockerfile for building runnerup

### PR DESCRIPTION
**Pull request by ericcurtin**

### CODE REVIEW

**Comment by gerhardol** [comment]
Cool!

I have no Linux installation myself (doubt I setup one too now) and will therefore not use it (of course a a Docker container for Windows could be setup but I have no need right now).

Someone else that can try it?

**Comment by ericcurtin** [comment]
I want to make it possible so you can build this on Linux via a single shell script, using Docker helps, I use the App myself, so might fix a bug or two if I encounter one! :)

**Comment by ericcurtin** [comment]
I haven't got this working yet myself, just was putting the feelers out to see if there is any interest. I'll get it working first...

**Comment by ericcurtin** [comment]
Getting "Could not find or load main class org.gradle.wrapper.GradleWrapperMain" at the moment, when I try and build via gradle

**Comment by gerhardol** [comment]
I like it, even if I do not plan to use Ubuntu at the moment.
It would be nice if someone could confirm that the functionality (instructions needed?) but I assume this PR will be merged anyway, it does not affect core functionality.

**Comment by ericcurtin** [comment]
Instructions to verify on any Linux distro:

Install docker
docker build -t runnerup .
docker run -it -v "$PWD:$PWD" runnerup /bin/bash
cd to_git_repo
export ANDROID_HOME=/usr/local/android-sdk/
gradle wrapper
./gradlew whatever you want to run

**Pull request merged**
