### PR TITLE
renaming to Synchronizer

### PR DESCRIPTION
**Pull request by paradix**
- interface Uploader to Synchronizer
  - class UploadManager to SyncManager
  - all Uploader classes get the suffix Synchronizer
  - all variables, constants, comments, methods etc. renamed to synchronizer

### CODE REVIEW

**Comment by paradix** [comment]
Sorry but still it won't merge automatically even thought it's based on current state of master.
Maybe it's due to file name changes, I don't know. But manual merge doesn't show any conflicts.

**Comment by jonasoreland** [comment]
ok...will check/try at home with computer then...

**Comment by paradix** [comment]
any luck? :)

**Comment by jonasoreland** [comment]
didn't find any computer time (@home)
maybe tonight

**Pull request merged**
