### PR TITLE
Final: Update for TCX & GPX export:

### PR DESCRIPTION
**Pull request by Uatschitchun**
This is the final version of #1054 

* Update KXmlSerializer with version from https://github.com/stefanhaustein/kxml2
* Update TCX.java for to format exported XML with indents and add Decice&Author (pytrainer seeme to need it)
* Fix for #1046 
* Fix for #332
* Import fixes from https://github.com/jonasoreland/runnerup/pull/386
* Fix some warnings regarding TODO
* Set version & build correctly in exported TCX
* Fix xsi:type
* Construct application name in TCX as: "ApplicationID - Version.Name - Version.Code". Might be handy ...
* Add missing tags and remove obsolete ones
* Add xsi:schemaLocation for completeness. Other TCX have it, too

### CODE REVIEW

**Comment by Uatschitchun** [comment]
Will this not be part of 2.4.3.1?

**Comment by Uatschitchun** [comment]
2.4.3.1?

**Comment by gerhardol** [comment]
An update is needed due to that he search is broken, but there is a bad Target 11 that requires son beta time  So maybe updated in the public release. 

I have been on the limit for sometime with real life and some other projects and this is not so easy to verify.

**Comment by gerhardol** [comment]
Finally got to look at the details, looking at the specs and other implementations.
Rebased removing the kml serializer as that was merged prior to this PR.
A few other changes to namespace

**Pull request merged**
