### PR TITLE
renaming to Synchronizer

### PR DESCRIPTION
**Pull request by paradix**
- interface Uploader to Synchronizer
  - class UploadManager to SyncManager
  - all Uploader classes get the suffix Synchronizer
  - all variables, constants, comments, methods etc. renamed to synchronizer

### CODE REVIEW

**Comment by jonasoreland** [comment]
"We can’t automatically merge this pull request. " ??

**Comment by paradix** [comment]
Yes, probably due to the changes from yesterday. Have a look at the branch graph an you'll know why.

**Comment by paradix** [comment]
I was able to merge automaticaly those branches on windows.
Maybe github has some problems.

**Comment by jonasoreland** [comment]
can you recreate/fix it so I can use the github merge ?

**Comment by paradix** [comment]
there are no conflicts at all. Github just can't do the fast forward. If you do merge per command-line or TortoiseGit it will work. It's easier for you than me recreating it. More risks I mess something up.

**Pull request closed without merging**
