### PR TITLE
Sdk version update to 24

### PR DESCRIPTION
**Pull request by gerhardol**
Few API changes from 23->24, so going with 24
Currently no specific needed from SDK 23, but there eventually will be

Most changes are due to the updated permission handling in SDK 23

Note that the commit contains other branches too (Swedish, lint). I hope that those are included first. The specific commits are from 3, 10, 17 July. (I have only really tested them together.)
However, this is partly for discussion, expect to resubmit after reviews.

### CODE REVIEW

**Comment by gerhardol** [comment]
Updated slightly, to handle the asynch permission handling better
Bundled workouts are not handled

However, for good functionality other AppCompat changes are needed (some commented out SnackBar handling in MainActivity requires this).

**Comment by gerhardol** [comment]
Latest fails as Travis cannot find build-tools 24.0.0 after 24.0.1 is released
Updating to 24.0.1 still fails...
https://github.com/gerhardol/runnerup/tree/travis-build-tools-24.0.1

**Comment by jonasoreland** [comment]
do you know when travis will support 24 ?

**Comment by gerhardol** [comment]
Travis supports SDK 24 fine. The build problem was started by build-tools-24.0.0 failing to be installed (at least temporary) after 24.0.1 was released, then me screwing up the update. I created PR  #410 for this.

I would like to make AppCompat theme (PR #409) a requirement for this PR, that will enable a nicer solution. (more comments there)

**Comment by jonasoreland** [comment]
this is dead, right ?

**Comment by gerhardol** [comment]
The changes are applicable, but I will update some to give a better MM experience
Will maybe rebase changes on master though, to get a cleaner commit

**Pull request closed without merging**
