### PR TITLE
Moved hr device code into its own module

### PR DESCRIPTION
**Pull request by xbao**
Hey, I'm wanting to use the HR device code in another application I'm writing. It's very self-contained, so moving it into it's own module to be included as an AAR was straight forward. The nice thing about the move for RunnerUp is all the build logic for the hr device stuff is out of the app's module. What do you think?

### CODE REVIEW

**Comment by jonasoreland** [comment]
the moving of
> compile files('../GraphView/public/graphview-3.1.jar')

seems really weird...other wise it looks good to me...

**Comment by xbao** [comment]
Yes, that was a mistake. I'll fix it up

**Comment by jonasoreland** [comment]
merged.

i'm just curious, what are you planning to use the HR code for ?
(and i hope you noticed that code is gpl3)

/Jonas

**Comment by xbao** [comment]
Yip, my app will be under the same license. I'm writing a continuous heart rate monitor, with the idea of providing a cheap and easy method of screening for sleep apnea ([Science!](http://circ.ahajournals.org/content/100/13/1411.short)). 

Basically just need the rr intervals, which BLE and Ant+ both support. The Ant+ API seems a bit fugly though. Three asynchronous callbacks for one data event does not for elegance make. 

It was just a bit of luck that I also use RunnerUp for tracking my running. Your HR device code is pretty excellent and I can't find anything similar, how would you feel about it moving to an external library?

**Comment by jonasoreland** [comment]
1) cool
2) is ok if we keep it like this for a while...and we can maybe make it
library later ?

/Jonas

**Comment by xbao** [comment]
Yeah no worries, simple is good

**Comment by jonasoreland** [comment]
hi there,
i tried to make a release today..and got this:
:app:proguardLatestRelease
Warning: com.samsung.android.sdk.bt.gatt.a: can't find superclass or interface android.bluetooth.IBluetoothStateChangeCallback$Stub
Warning: com.samsung.android.sdk.bt.gatt.d: can't find superclass or interface android.bluetooth.IBluetoothStateChangeCallback$Stub
Warning: com.samsung.android.sdk.bt.gatt.BluetoothGatt: can't find referenced class android.bluetooth.IBluetoothManager
Warning: com.samsung.android.sdk.bt.gatt.BluetoothGatt: can't find referenced class android.bluetooth.IBluetoothManager$Stub
Warning: com.samsung.android.sdk.bt.gatt.BluetoothGatt: can't find referenced class android.os.ServiceManager
...lots of more...
Warning: there were 22 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 4 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)

---

do you know how to fix ?
(or else i'll revert it until we get it sorted)

/Jonas

**Comment by xbao** [comment]
Yikes, sorry about that. I'll have a look, if I can't figure it out in the next half hour do a revert

**Comment by xbao** [comment]
Looks like this is going to take a bit of debugging, maybe do a revert?

**Comment by xbao** [comment]
Hey @jonasoreland, if we add 

```
-dontwarn com.samsung.**
```
to `app/proguard.txt` it'll fix it. Shouldn't break anything, library's only used in a few versions of Android and it's only complaining about a few classes. More info is at xbao/runnerup#1 if you're interested

**Comment by jonasoreland** [comment]
ok. thx for the investigation!

/Jonas

**Pull request merged**
