### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by sdebaerd**
Added some missing translated texts in Dutch

### CODE REVIEW

**Comment by gerhardol** [comment]
Can you please add these on Transifex?
See https://github.com/jonasoreland/runnerup/wiki

There are some changes i master not pushed to sources yet, as that will remove some strings slightly changed English strings where the translations are mostly OK.

**Comment by sdebaerd** [comment]
Overlooked it, my apologies. I signed up and requested to join the projectteam.

**Comment by sdebaerd** [comment]
Added the translations

**Comment by gerhardol** [comment]
I had prepared a 2.4.3 release, will update it with these translations too. 
To be released as a beta tonight.
The paired/non-paired BLE handling maybe need to be separated before a public release, otherwise I expect a week for the public release.

**Pull request closed without merging**
