### PR TITLE
Downloader activities and default uploader

### PR DESCRIPTION
**Pull request by paradix**
renaming to synchronizer will follow in next PR's

### CODE REVIEW

**Comment by jonasoreland** [comment]
Getting there...

1) as previous, add GPL headers to new files
you can put copyright paradix@

2) i think the Pair<> construct is quite ugly for return value of uploadActivity
Could we add an mID the Status enum instead ?

/Jonas

**Comment by paradix** [comment]
Don't know if you noticed, but I have made the changes concerning the Pair "pattern".
Waiting for this to be merged so, I can pull the other changes I made for the RunKeeper downloader.

**Comment by jonasoreland** [comment]
did notice,
is travelling, and haven't found time, sorry

/Jonas

**Comment by paradix** [comment]
I assumed you were busy. Just wanted to make sure you got the changes.

**Pull request merged**
