### PR TITLE
Manual distance picker miles

### PR DESCRIPTION
**Pull request by gerhardol**
Manual add distance picker mixed miles and meters

Also set defaults

Still presented as m without unit, but that is a general setup
TitleSpinner: mValue should be split in the presentation and value.

### CODE REVIEW

**Comment by jonasoreland** [comment]
the usage of 1000 has to be wrong ?

**Comment by gerhardol** [comment]
The change is to instead of entering meters for the minor unit is to enter thousands. So if you set 1.002 miles this would be 1612m.
An alternative would be to let the picker just set complete km/miles and parse the string.

**Comment by gerhardol** [comment]
Any comment on this?

**Comment by gerhardol** [comment]
Any suggestion how to not mix miles and meter?
One field with miles/km where the advance affects complete km/miles?

**Comment by gerhardol** [comment]
Suggestion: This should be reworked to have one field only but +/- steps complete km/miles

**Comment by magnacustos** [comment]
Any update on this. Because it shows as m instead of mi when I upload to runalyze it throws off the distance.

**Comment by gerhardol** [comment]
My pull request was rejected, I still consider this as a bug though. How should it look like?

**Comment by gerhardol** [comment]
Superseded by #624

**Pull request closed without merging**
