### PR TITLE
Cleanupsettings

### PR DESCRIPTION
**Pull request by bagage**
As stated in #317: remove "extra sports settings" and use it always instead.

### CODE REVIEW

**Comment by jonasoreland** [comment]
1) I like it
but
2) Can't we keep the experimental features checkbox/setting ?
I think we're going to need it again in the future...

/Jonas

**Comment by bagage** [comment]
2) the thing is ... no-one actually use it if he/she cannot know what the settings will actually enable. I think it's better to add custom setting each time it's needed. I'm not sure many people except me used it until today... wdyt?

**Comment by jonasoreland** [comment]
I'd say keep it... (maybe add the comment for the checkbox that it's
currently unused )
Ok?

**Comment by bagage** [comment]
Added back.

**Pull request merged**
