### PR TITLE
Migrate to AndroidX Preference library

### PR DESCRIPTION
**Pull request by roberi**
Starting with Android 10, the platform android.preference library was deprecated. With this update, the AndroidX Preference library will be used instead for everything related to settings (preferences).

It is a relatively large update with many new and changed source code files. The main workflow has been to replace each nested PreferenceScreen in settings.xml with a PreferenceFragmentCompat using it's own XML resource.

Related issues: #1146 and #648.

### CODE REVIEW

**Comment by gerhardol** [comment]
Thanks. Looks the same what I see.
I just got A14 to my phone so I will run all updates together (and I have the back exit issue too).

**Comment by gerhardol** [comment]
Works what I see. Not sure how I can review this, especially where code were moved to new files. I have just tried to diff a few changes, some manual testing.
May merge and have a longer beta period.

Also started with targeting Android 14 (prepared before, not tested). 
Back-and-hold will leave an app, but not multiple back.
Pushed a branch to my repo.

**Comment by roberi** [comment]
> Not sure how I can review this, especially where code were moved to new files.

Is there anything I can do to help or make things easier?

**Comment by gerhardol** [comment]
> > Not sure how I can review this, especially where code were moved to new files.
> 
> Is there anything I can do to help or make things easier?

No, I plan to try to diff some more. It is hard to see if all moved code is equivalent, or wheat to test. But it works for me so guess I will just merge it.

Nice to see the separation of commits in the PR for reviewing. If you want to squash some commits for a rebase merge, please go ahead. I could squash all or rebase all too.

**Comment by gerhardol** [comment]
> > I could squash all or rebase all too.
> 
> Yes, please do that.

Which do you prefer?

**Comment by roberi** [comment]
I did not fully understand the difference at first (my first time). =)

For me, it does not matter. Perhaps squashing all commits into one? But feel free to do what you consider to be best.

**Comment by gerhardol** [comment]
Thanks for this!
Squashed with a manual commit summary.
Diffed most split files.

**Pull request merged**
