### PR TITLE
Use fragments in MainActivity

### PR DESCRIPTION
**Pull request by daverix**
In order to be able to create a better UI, the first step is to use fragments. This PR will make the app look like this to start with: https://photos.google.com/share/AF1QipMULPT_AQ8vHM6-kmJmzUxCyDCrQaQ89c1XThXjmImpsJGnkXZUD3tfZDgbb6rMgg?key=TTl0Z1Uxa0oteC03XzItTWREYnJvQWpwRkZ4MjRB

I hope upgrading android version target isn't a problem...

### CODE REVIEW

**Comment by jonasoreland** [comment]
i would love to start merging this...but I'm stuck on https://github.com/jonasoreland/runnerup/issues/317

**Comment by jonasoreland** [comment]
Hi,
Can you update this??
now that it looks like v1.49 is finally getting releasable

/Jonas

**Comment by daverix** [comment]
Done :)

**Comment by jonasoreland** [comment]
and...same question about supportfragment (manager)...
is that no longer needed for apps supporting old and new devices ??

**Comment by daverix** [comment]
When using a support fragment, it's LoaderManager is of the support library type so we still use the support fragment manager etc.

**Comment by jonasoreland** [comment]
I don't understand: "Now we still use a froyo version because of some google play things, but if we can solve that too then we only need one flavor."

1) your current PR doesn't break froyo ?

**Comment by daverix** [comment]
No it shouldn't.

**Comment by jonasoreland** [comment]
fyi, was about to merge this...but it had conflicts. will merge manually tonight (or as soon as i find time).

**Comment by jonasoreland** [comment]
tried merging...and found that size of APK increases a lot....specially for froyo
froyo: 1014K => 1.8M (80% increase)
latest: 3.5M => 4.1M (17% increase)

Do you why ??

**Comment by daverix** [comment]
Probably because newer support library have more code and proguard is not
running minimize for support libs?

**Comment by jonasoreland** [comment]
hmm...can you fix so that froyo does not increase as much ?

**Comment by daverix** [comment]
I can take a look in the weekend.

**Comment by daverix** [comment]
Rebased against master, will check apk sizes now.. Is it release you checked?

**Comment by jonasoreland** [comment]
yes, I checked release...
froyo: v1.50 1014K
latest: v1.50 3.5M

**Comment by daverix** [comment]
I have now managed to get down the sizes to the following:

froyo debug: 2.8MB
froyo release: 1.9MB

latest debug: 4.3 MB
latest release: 3.4MB

I think the reason for the larger file sizes corresponds to all new image resources used to get the material design look and feel on devices with version lower than Android 5.0.

**Comment by jonasoreland** [comment]
hmm...froyo is almost twice as big...

i think people on older devices generally like the small footprint...
but does 2Mb vs. 1Mb matter,

wdyt ?

/Jonas

**Comment by daverix** [comment]
I don't know how many still uses old froyo phones but I don't think it
matter much if its 2mb instead of 1mb.

**Comment by nebmo** [comment]
Jonas, I think you have to decide if you want new looks or small app. Can't have both..

**Comment by jonasoreland** [comment]
damn in...should have made these comments prior to merge.
1) missing target annotations! (the ones causing https://github.com/jonasoreland/runnerup/issues/324)
2) the account list in DetailActivity, is super small on my phone. Almost not usable
3) the notes field in DetailActivty is hard to see (it is no longer white)

Can you fix ?

**Comment by daverix** [comment]
1) I didn't cause it, but I could look at it, just not right now...
2) I will go through my changes real quick to see what caused it.
3) Does #328 work for you?

**Comment by daverix** [comment]
2) Does #329 look ok?

**Comment by jonasoreland** [comment]
1) I know you didn't cause that one.
But your patch (that I merged) removed @TargetApi(Build.VERSION_CODES.FROYO) annotations.
And it was *missing* annotations that made us not notice the build failure.
Conclusion: We should have the annotations everywhere, then we get build failure rather
than runtime failures.

2) I commented your other fixes individually.

/Jonas

**Comment by bagage** [comment]
1) concerning that I know it's my fault, but since I never build Froyo personally I do not see them (my fault)..and travis build seems fine with it. 
Do you know any way to detect these invalid API calls from android studio? We could change travis configuration so that it fails in that case.

**Comment by jonasoreland** [comment]
the target annotations makes build fail
if using incorrect apis...

**Comment by jonasoreland** [comment]
pingeling.

how is progress on this? many things are still missing to make this good.
maybe I should rollback and you can fix thing wo/ me harassing ?

/Jonas

**Comment by jonasoreland** [comment]
reverted...see https://github.com/jonasoreland/runnerup/commit/c8cc63f0e0d77d2f9a453714159c9f47ad5ee6a1.

**Pull request merged**
