### PR TITLE
issue #1084: TTS Installed but not detected

### PR DESCRIPTION
**Pull request by rickyepoderi**
Issue: #1084 

Just adding the TTS_SERVICE to the app `AndroidManifest.xml` and two minor modifications to control better the error with the TTS object.

This works for me in lineageos 18.1 / Android 11.

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]
Looks good.
Did you check the error handling for normal activities too?
(status is checked there and the tracker state is set to error, so it looks OK to me).

**Comment by rickyepoderi** [comment]
> Did you check the error handling for normal activities too?

I just saw the status was checked in the `TrackerTTS` callback, not looked into that deeply. But I can say that now it works for me in running activities too, it speaks at start, stop, resume and the lap summary (only tested in my real device, that's what I have configured there). In general it was running OK before in Android 10 so I think just the xml stanza is really needed, although I also added the two others checks for completeness.

**Comment by gerhardol** [comment]
> > Did you check the error handling for normal activities too?
> 
> I just saw the status was checked in the `TrackerTTS` callback, not looked into that deeply. But I can say that now it works for me in running activities too, it speaks at start, stop, resume and the lap summary (only tested in my real device, that's what I have configured there). In general it was running OK before in Android 10 so I think just the xml stanza is really needed, although I also added the two others checks for completeness.

So it just did not work before, there should be a printout like `state.set(ERROR`
Leave it at this, will prepare a release. (even if Pebble is not resolved it seems)

**Comment by rickyepoderi** [comment]
Ah! Yes, it didn't speak at all since I upgraded the device to lineageos 18.1 / android 11. The activity was recorded OK but without TTS. :smile:

Thanks for looking this!

**Pull request merged**
