### PR TITLE
Runtastic update

### PR DESCRIPTION
**Pull request by dhiltonp**
I used "CharlesProxy" to intercept SSL traffic (vs. static code analysis).

It looks like 2 things have changed for the login - the URL, and a key/value pair has been added.

This code is untested, as I don't have a good android dev setup right now.

### CODE REVIEW

**Comment by dhiltonp** [comment]
Should fix #389.

**Comment by jonasoreland** [comment]
Hi,
I merged and tested it. Short answer: it didn't work.
I then reverted the URL change, which made it better. Then it's stuck at getting user id.
(after url2)

**Comment by dhiltonp** [comment]
Ok.

It looks like the "user" key has been changed for "current_user"

    userId = ret.getJSONObject("user").getInt("id");

should be 

    userId = ret.getJSONObject("current_user").getInt("id");

**Comment by jonasoreland** [comment]
i don't get a json document back from the http-request (99% sure)
so there is something broken earlier

/Jonas

**Comment by dhiltonp** [comment]
See email

**Comment by jonasoreland** [comment]
will try find time this weekend...
i might have seen something.

**Comment by sunfish62** [comment]
RunnerUp 1.57 seems to still exhibit this login failure to Runtastic...

**Comment by jonasoreland** [comment]
yea...
i had an idea...but now I have forgotten what it was...
hopefully some runtastic user can pick it up...

**Comment by jeee** [comment]
can't login to Runtastic either.

**Pull request merged**
