### PR TITLE
Store prefs_mute as boolean, show it as checkbox

### PR DESCRIPTION
**Pull request by johnlepikhin**
Current implementation is very complicated and furthermore it simply doesn't work in non-English locales (at least in locales where "yes" is written with different characters).

### CODE REVIEW

**Comment by johnlepikhin** [comment]
Probably related issue #394 (some people reported that feature doesn't work for them)

**Comment by jonasoreland** [comment]
maybe paranoid, bur how about changing the value of pref_mute to a new string,
and use the old value verbatim when converting. this to minimize risk that getBoolean is
used on yes/no string ?

**Comment by johnlepikhin** [comment]
Done. Note, you must add resource string/pref_mute_bool. I have no idea how to add it.

**Comment by jonasoreland** [comment]
to add a new "pref_key" you edit (these are not translated)
app/res/values/pref_keys.xml

to add a new string you edit (these are translated)
common/src/main/res/values/strings.xml

it's that easy...and then someone else will do translation for you...

now you can update #478 too, right ?

**Comment by johnlepikhin** [comment]
Thanks, done.

**Pull request merged**
