### PR TITLE
Material menus

### PR DESCRIPTION
**Pull request by 12people**
Adding a new Material Design look for menus, leaving behind the old Froyo design:

screenshot_20180407-021556

Based on the [text field box](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes) view described in the material design guidelines.

Also darkened the background in the "Advanced" tab (see screenshot), so that the now white text is easily visible.

### CODE REVIEW

**Comment by gerhardol** [comment]
Looks fine

**Comment by 12people** [comment]
@gerhardol 

How does the approval process work here? How do I get my changes accepted to the repo? Does @jonasoreland approve all PRs?

**Comment by gerhardol** [comment]
I can approve and merge. For me this ok in principle. 
However, I cannot build signed releases or put it on play. It would be good to resolve this before putting in too much work. Since you have started it would be good to fix this shortly. I have done a number of other corrections and improvements too, some not even pushed and would like to align the changes.

**Comment by 12people** [comment]
OK. I don't really mind the changes not being signed or on the Play store. I'd really like the changes pushed so that 1) I can make other PRs that build on work that I've done and 2) there aren't any merge conflicts as new PRs are submitted.

Could you please merge my changes into master? If it turns out building signed releases is impossible, we could just fork the entire repo later.

**Comment by Marx2** [comment]
Please merge and contact maintainer to release beta. Don't waste work of
new developers. I see a few which contribute quite interesting things which
can make RunnerUp outstanding. If maintainer have no time, we can kindly
ask him to grant his rights to another person, at least temporarily. I
would stay away of forking as long as possible, because RunnerUp has it's
name and fame, let's build up on it.

sob., 21.04.2018, 14:06 użytkownik Mirek Mazel <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
Merged, did a follow-up commit to prepare for merging with the master_ng branch
Continue with the updates

I really would like to merge master_ng:
 * The corrections, including all Lint
 * Android 8 corrections

Further:
 * Minimum Android to be discussed, maybe 4.1 is sufficient for some time, it should support Google support libs
 * Drop Froyo build
 * Skip SamsungBLE (4.2)
 * Android Studio 3.1

But this is for another

**Comment by 12people** [comment]
If you merge to master_ng as well, that's completely fine with me.

I'd love for the minimum Android version for NG to be Android 4.1. Google supports it very well through its support libraries, I haven't run into a case where I'd need a higher minSDK.

While we're at it, could you also please merge #649 ?

**Comment by 12people** [comment]
Or did you mean merge master_ng into master?

If the two are merged, then it's important to me that the minSDK be Android 4.0, if not lower.

Do we have current Android version usage numbers for RunnerUp?

**Comment by gerhardol** [comment]
> Or did you mean merge master_ng into master?
If the two are merged, then it's important to me that the minSDK be Android 4.0, if not lower.
Do we have current Android version usage numbers for RunnerUp?

Yes, master_ng branch has other corrections

The min version can be set to 4.0, should follow the version of the support libs, currently 4.0 (not 4.1). Not sure when that will raise the next time though

Jonas posted Play statistics some years ago, I cannot find it now.
Compared to the overall statistics:
https://developer.android.com/about/dashboards/index.html

there were more <4.0 users in RU than in general for Android, but also that has dropped.
I do not find it worth the effort to develop new features for the Android versions not supported by support libraries.

**Comment by 12people** [comment]
I agree, though with one small request: before we move to minSDK of 4.0, I'd like to make one more release for Froyo. I've put work into making sure my contributions are Froyo-compatible (including one pull request that hasn't been submitted yet), and I'd hate for that work to go to waste.

**Comment by gerhardol** [comment]
The RU statistics:
https://github.com/jonasoreland/runnerup/pull/404#issuecomment-236534149

Historical at that point:
https://www.bidouille.org/misc/androidcharts

**Pull request merged**
