### PR TITLE
Basic entity concept

### PR DESCRIPTION
**Pull request by paradix**
Awaiting acceptance ;)

### CODE REVIEW

**Comment by paradix** [comment]
Haha that was quick and easy

**Comment by jonasoreland** [comment]
there a limit to how much time i can spend on it too...
i wasn't super keen on the implemented but it as KISS...and manageable in
size...

/Jonas

**Comment by paradix** [comment]
So maybe find a bit more time later and let's do it in a way you want it to be done?

**Comment by jonasoreland** [comment]
yea...or not :)

**Pull request merged**
