### PR TITLE
adds uploads to WebDav

### PR DESCRIPTION
**Pull request by ticevi**
First try in adding WebDav Support,
Upload is working with nextcloud but needs more testing.

fixes https://github.com/jonasoreland/runnerup/issues/327

### CODE REVIEW

**Comment by gerhardol** [comment]
Any NextCloud service that works?
I cannot get the one I signed up to working, any hints on the URL?

If this is experimental, it could be disabled by default.
As this is based on existing uploaders, I see no problem.

**Comment by ticevi** [comment]
The Url for WebDav with nextcloud should look similar to this: https://%domain%/remote.php/dav/files/%username%/%folder%
WebDav does not support to create more than one folder at once. -> the base folder must exist

**Comment by gerhardol** [comment]
When I tried to upload files yesterday, the uploader did not report any errors, but the file did not appear in the NextCloud implementation. I did not debug it then, but today it worked.
Not much error handling - similar to the existing though, maybe a fluke.
It would be nice to add the link to the file as an external ID (similar should be added for DropBox). With both both tcx/gpx, one of them should be selected.

**Comment by gerhardol** [comment]
Thanks
Could not recreate the upload problem
I considered adding references to the uploaded file, but that is a later enhancement

**Comment by ticevi** [comment]
Thanks for merging 👍
I am currently busy with work and uni. When I have some spare time I will look into adding the references und doing some code cleanup for a more robust upload

**Pull request merged**
