### PR TITLE
Activate sport types walking, orienteering for most languages

### PR DESCRIPTION
**Pull request by gerhardol**
Transifex needs to be updated too
If "sportEntriesExperimental" was not translated, the standard appears still.
Also remove "Not_much_to_say_at_this_point", no longer used (warning in some situations)
Facebook activity type set to Biking only for Biking (was biking for all other than Running before. Could have set Other to Biking but most of the code handles Other as Running)

### CODE REVIEW

**Comment by ataliba** [comment]
Amazing :) I need this to use the portuguese language on my phone :+1:

**Comment by gerhardol** [comment]
Any comments on this?

Other Transifex are required too
I can make a cleanup if I get admin access at Transifex

**Comment by jonasoreland** [comment]
can you request transifex access ?

**Comment by gerhardol** [comment]
I have transfer as a user

**Pull request merged**
