### PR TITLE
lint: enable lint checking on travis and fix various errors

### LINKED ISSUE #324: Bug: Widget added to master doesn't work on froyo
It uses APIs that doesn't exist in froyo... Either the widget should be latest flavor only or the widget should use apis supported on froyo...

```
09-19 13:53:24.911 1208-1208/org.runnerup E/dalvikvm: Could not find class 'org.runnerup.feedwidget.FeedWidgetService', referenced from method org.runnerup.feedwidget.FeedWidgetProvider.onUpdate
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime: FATAL EXCEPTION: main
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime: java.lang.NoClassDefFoundError: org.runnerup.feedwidget.FeedWidgetService
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at org.runnerup.feedwidget.FeedWidgetProvider.onUpdate(FeedWidgetProvider.java:84)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at org.runnerup.feedwidget.FeedWidgetProvider.onReceive(FeedWidgetProvider.java:74)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:1794)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.access$2400(ActivityThread.java:117)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:130)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:3683)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:507)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
09-19 13:53:24.931 1208-1208/org.runnerup E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by bagage**
This fixes #324 and enable lint checking on travis to avoid it in the future.

I also changed cues  plurals (according to lint) so after merging this, you will have to push new sources to Transifex.

The last error which causes Travis to fail is an issue in Transifex probably, I contacted their support and waiting for a reply (within the week) so please do not merge this yet!

### CODE REVIEW

**Comment by jonasoreland** [comment]
why did you remove cueResources ? that is removing a feature.
with it, you can have audio cues in one language and gui in another.

**Comment by bagage** [comment]
Hmm, indeed I did that because Android Studio refused to regenerate cueResources and I though this was the only way to make it happy. I did not thought that audio and GUI could be actually different... thanks for noting that.

**Comment by bagage** [comment]
1) Issue should be fixed now.
2) I reenabled sv-SE language (Swedish) - why was it disabled? Should it be still disabled?
3) Still waiting for Transifex answer

**Comment by jonasoreland** [comment]
1) How is this going ?? Now that nebmo fixed pebble, I somewhat eager to release!
maybe you can fix froyo in a separate PR...then I can release...
and you can carry on with this in parallel ?

2) swedish was disabled cause translations was not very good (imo...as a native swedish speaker).

**Comment by bagage** [comment]
1) transifex need a few more days 
2) OK, then I think it is great to keep it. If translation is really wrong, it would be better to remove it from transifex to ease new translation ;).

In the mean time I think you can merge this - travis will fail for a few days but that's not a major issue - we know why it is failing. If you do not want it to fail, I can temporary disable the error for PL plural issue, but I do not think it's worth the trouble since we will have to add it back in a few days/weeks?

Please do not forget to push new translations to transifex when accepting this PR!

**Comment by jonasoreland** [comment]
I prefer if you make a separate PR with just the fixes for froyo
and then we do the others afterwards...

is that ok ?

**Comment by bagage** [comment]
I do not have much time this week, I'll try to do that coming week.

**Comment by jonasoreland** [comment]
ok, np

**Comment by jonasoreland** [comment]
what is status on this now ?
- if I can choose, i would really like the "%d meters"-thing in separate patch...

**Comment by bagage** [comment]
Well I guess it takes time at Transifex to fix these plural issues, nothing has moved much since. Maybe we should disable them for now?

**Comment by gerhardol** [comment]
Lint enabled on Travis in #400, #402 (credit here even if I did not use this patch). 
Further lint warning removal in #403 
No translation related in any of these PR.
I have updated the Swedish translation on Transifex (will take another look)

What remains primarily in this PR is the translation quantity updates. I guess this is just "todo"

If making that change, the builtin unit to strings like "Intervall distance (m)" should use "m" as a parameter. (Maybe not same PR, but simultaneously).

**Comment by gerhardol** [comment]
The changes in this PR are now merged, the PR can be closed.

**Comment by gerhardol** [comment]
Changes are included already, many  more in #524 
Closing

**Pull request closed without merging**
