### PR TITLE
Adding a new runnerupweb account (with URL).

### PR DESCRIPTION
**Pull request by rickyepoderi**
Hi guys,

I use runnerup for my running activities but I miss the possibility of having my own server backend. I mean, I have a FOSS application for running but I cannot upload my activities to my own server (and I have to use a cloud service I don't trust on). For that reason I started a little PHP/JavaScript application that emulates the Digifit account. More or less it is working right now but I need to modify the hosts file (making the phone think my server is digifit). 

See this blog entry for more information:
http://blogs.nologin.es/rickyepoderi/index.php?/archives/126-RunnerUpWeb.html

And the source code for the backend application is here:
https://github.com/rickyepoderi/runnerupweb

Now I think it's time to add my backend as a regular citizen in the app. I prepared this pull request just as a first approximation to the problem. The main issue is that reunnerupweb can be installed in any box (it has no fixed URL like digifit, endomondo or any other cloud service). For the moment I have extended the AuthConfig information to also include the URL and I have added a new authentication method (USER_PASS_URL). The screen that requests for username/password now also asks for the URL if necessary.

Another problem that drove me crazy was adding the image for my account (if I used aXX_runnerupweb.png) the accounts images were mixed up (it was like they were ordered lexicographically in the upgrade). That's why I renamed the image to b01_runnerupweb.png. Sorry but I don't usually develop for android (recommendations are welcome). :-(

As I've said this is just my first try, if you see it can be improved or you think the problem can be easier resolved using another way just tell me.

Thanks in advance!

### CODE REVIEW

**Comment by Marx2** [comment]
To go open source the best would be to integrate with Runalyze. It's open source, free, actively maintained. It also has possibility to upload track, so import function already exists.
It would require separate connector with possibility to set address.
I've already made export from Strava (filled by RunnerUp) then import to Runalyze and everything went ok.

**Comment by rickyepoderi** [comment]
Damn it! I did not find any backend application to store my activities when I looked for it. It's the first time I hear about runalize. Nevertheless my little application draws fantastic maps using OSM. :-)

I don't know, let's see what other people think about that.

**Comment by Marx2** [comment]
If you check http://blog.runalyze.com/ , you'll see they also have map :)
While it's in german language, google translate is quite helpfull there, and Runalyze is fully translated itself.
If you have enough skills, it would be VERY helpfull to have integration between RunnerUp and Runalyze, they seems to perfectly fit each other.
Runalyze is free, and has so many options that Strava nor Endomondo can beat it in some areas. It doesn't have so much social features, but if you like privacy, you probably don't care...

**Comment by rickyepoderi** [comment]
I think it's more profitable to work on issue #300. So I'm going to close this request. Thanks all.

**Pull request closed without merging**
