### PR TITLE
Added edit button for existing advanced workouts

### PR DESCRIPTION
**Pull request by Upabjojr**
This PR adds the possibility of opening the existing advanced workouts in edit mode.

Fixes https://github.com/jonasoreland/runnerup/issues/352

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]
Looks good
Can you rebase on master?

**Comment by Upabjojr** [comment]
OK, I think it's rebased.

**Comment by gerhardol** [comment]
Thanks!

**Comment by opoto** [comment]
Hi. Nice PR, thanks!
However I think the "Discard" button in the edit screen is confusing: I was assuming it would discard edits, while it actually deleted the workout. Is this intentional? I think deletion should not be possible from edit screen, but only from the workout list, where there is a proper "Delete" button.

**Comment by Upabjojr** [comment]
Well, all this PR does is adding an edit button to allow the creation screen to reappear even after the workout has been created. The edit screen is exactly the same as the creation screen.

Maybe in this case the discard button should be hidden, indeed.

**Comment by opoto** [comment]
Better than removing that button, I would expect it to be present and implement what was expected: cancel current edits and restore previous workout state. For a new workout it means cancelling workout creation, but for an existing edited one it would mean restore state as before entering the edit screen. 
I understand this might be more complex to implement.

**Comment by Upabjojr** [comment]
> Better than removing that button, I would expect it to be present and implement what was expected: cancel current edits and restore previous workout state. For a new workout it means cancelling workout creation, but for an existing edited one it would mean restore state as before entering the edit screen.
> I understand this might be more complex to implement.

The problem is that it is in autosave mode.

**Comment by opoto** [comment]
Ok, I understand it would imply deeper changes.
Removing the button is the best option for now then.
Thanks

**Pull request merged**
