### PR TITLE
Final: Preferences updates

### PR DESCRIPTION
**Pull request by Uatschitchun**
Second try for the preference updates. Suggestions from first try https://github.com/jonasoreland/runnerup/pull/1048 added

### CODE REVIEW

**Comment by Uatschitchun** [comment]
I would suggest to "risk" missing translations, as this will hopefully motivates translators to update. German translation had a huge update in transifex and helps understanding settings and usage together with this preference update. 
Translating the new strings in german is a matter of minutes
What about adding a link to https://www.transifex.com/runner-up/runner-up-android/dashboard/ into ABOUT?

**Review by gerhardol — APPROVED** [review]
I will have to review the pending changes before merging though.
Maybe the current beta can be promoted to production soon (the previous beta had a crash.)

**Comment by Uatschitchun** [comment]
@gerhardol am going for a run this morning and will test the latest fix regarding cadence.

**Comment by Uatschitchun** [comment]
Will this not be part of 2.4.3.1?

**Comment by gerhardol** [comment]
Finally got to cleanup this PR.
There were many minor issues that was difficult to comment on, so I pushed changes
There will be a few other changes in some private PRs too

The big issue is that the SettingsActivity is deprecated and need to be replaced with fragments,

**Pull request merged**
